# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5205922eddb3518b048814f5e04b461be4132af06316a77479b5f287aa5380b496bca055fe41c495c9209d10c1a92d97e7c917a03c070f0c5845ccdaff71b12

test:
  secret_key_base: caf3c802912a9dd87a41871cfe44ea2da76b05daf18219448645857efc32b6025388d1b3d052dc7a269de5c77d4325b7f17897d5f9d58ae912c3d2ad6621921e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
